// Faffmaster layout - see readme.org
#include QMK_KEYBOARD_H

enum faffmaster_layers {
  _PRIMARY,
  _MOVEMENT,
  _MOUSE,
  _SYMBOLS,
  _NUMBERS,
  _FUNCTION,
  _MEDIA,
  _SPECIAL
};

// Modifier keys, just defined to keep the LAYOUTs more tidy
#define KC_LG_A LGUI_T(KC_A)
#define KC_LA_S LALT_T(KC_S)
#define KC_LC_D LCTL_T(KC_D)
#define KC_LS_F LSFT_T(KC_F)

#define KC_LS_J LSFT_T(KC_J)
#define KC_LC_K LCTL_T(KC_K)
#define KC_LA_L LALT_T(KC_L)
#define KC_LG_SC LGUI_T(KC_SCLN),

// Layers
#define L1_G LT(1, KC_G)
#define L2_R LT(2, KC_R)
#define L3_V LT(3, KC_V)
#define L4_H LT(4, KC_H)
#define L5_U LT(5, KC_U)
#define L6_M LT(6, KC_M)
#define L7_SLSH LT(7, KC_SLSH),
#define L7_Z LT(7, KC_Z)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_PRIMARY] = LAYOUT (
	KC_Q,		KC_W,		KC_E,		L2_R,		KC_T,			KC_Y,		L5_U,		KC_I,		KC_O,		KC_P,
	KC_LG_A,	KC_LA_S,	KC_LC_D,	KC_LS_F,	L1_G,			L4_H,		KC_LS_J,	KC_LC_K,	KC_LA_L,	KC_LG_SC,
	L7_Z,		KC_X,		KC_C,		L3_V,		KC_B,			KC_N,		L6_M,		KC_COMM,	KC_DOT,		L7_SLSH,
										KC_TAB,		KC_BSPC,		KC_SPC,		KC_ENT
  ),
  [_MOVEMENT] = LAYOUT (
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		C(KC_Z),	C(KC_X),	C(KC_C),	C(KC_V),	C(KC_Y),
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_LEFT,	KC_DOWN,	KC_UP,		KC_RGHT,	KC_INS,
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_HOME,	KC_PGDN,	KC_PGUP,	KC_END,		KC_DEL,
										KC_TRNS,	KC_TRNS,		KC_TRNS,	KC_TRNS
  ),
  [_MOUSE] = LAYOUT (
	KC_TRNS,	KC_ACL0,	KC_ACL1,	KC_TRNS,	KC_TRNS,		KC_TRNS,	KC_WBAK,	KC_WFWD,	KC_BTN3,	KC_TRNS,
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_MS_L,	KC_MS_D,	KC_MS_U,	KC_MS_R,	KC_TRNS,
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_WH_L,	KC_WH_D,	KC_WH_U,	KC_WH_R,	KC_TRNS,
										KC_BTN3,	KC_TRNS,		KC_BTN2,	KC_BTN1
  ),
  [_SYMBOLS] = LAYOUT (
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_GRAVE,	KC_LCBR,	KC_RCBR,	KC_PIPE,	KC_AMPR,
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_QUOT,	KC_LPRN,	KC_RPRN,	KC_TILD,	KC_BSLASH,
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_DQUO,	KC_LBRC,	KC_RBRC,	KC_UNDS,	KC_TRNS,
										KC_TRNS,	KC_TRNS,		KC_TRNS,	KC_TRNS
  ),
  [_NUMBERS] = LAYOUT (
	KC_LBRC,	KC_7,		KC_8,		KC_9,		KC_RBRC,		KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
	KC_COLN,	KC_4,		KC_5,		KC_6,		KC_DOT,			KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
	KC_MINUS,	KC_1,		KC_2,		KC_3,		KC_EQUAL,		KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
										KC_0,		KC_DOT,			KC_TRNS,	KC_TRNS
  ),
  [_FUNCTION] = LAYOUT (
	KC_PSCREEN,	KC_F7,		KC_F8,		KC_F9,		KC_F10,			KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
	KC_TRNS,	KC_F4,		KC_F5,		KC_F6,		KC_F11,			KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
	KC_TRNS,	KC_F1,		KC_F2,		KC_F3,		KC_F12,			KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
										KC_TRNS,	KC_ESC,			KC_TRNS,	KC_TRNS
  ),
  [_MEDIA] = LAYOUT (
	KC_TRNS,	KC_MUTE,	KC_VOLD,	KC_VOLU,	KC_TRNS,		KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
	KC_TRNS,	KC_MPRV,	KC_MPLY,	KC_MNXT,	KC_TRNS,		KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
	KC_TRNS,	KC_TRNS,	KC_MPLY,	KC_TRNS,	KC_TRNS,		KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
										KC_TRNS,	KC_TRNS,		KC_TRNS,	KC_TRNS
  ),
  [_SPECIAL] = LAYOUT (
	RESET,		KC_SLEP,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_SLEP,	RESET,
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,		KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,	KC_TRNS,
										KC_TRNS,	KC_TRNS,		KC_TRNS,	KC_TRNS
  )
};

const uint16_t PROGMEM qp_combo[] = {KC_Q, KC_P, COMBO_END};
combo_t key_combos[COMBO_COUNT] = {COMBO(qp_combo, KC_CAPS)};

/* Local Variables: */
/* c-basic-offset: 2 */
/* End: */
